//  Generated by Tools/IconGenerator/app_icons.py --swift. Don't edit by hand:
//  change the icon there and regenerate.

#if os(iOS)
extension AppIconChoice {
    static let yearRound: [(title: String, icons: [AppIconChoice])] = [
        ("Aquarium", [
            classic,
            .init(iconName: "AppIcon-Ink", title: "Ink", blurb: "Just the mark"),
            .init(iconName: "AppIcon-Gold", title: "Gold", blurb: "The premiere edition"),
        ]),
        ("Finishes", [
            .init(iconName: "AppIcon-Chrome", title: "Chrome", blurb: "Buffed to a mirror shine"),
            .init(iconName: "AppIcon-Onyx", title: "Onyx", blurb: "Black tie, black stone"),
            .init(iconName: "AppIcon-Blueprint", title: "Blueprint", blurb: "Drawn to scale"),
            .init(iconName: "AppIcon-Sapphire", title: "Sapphire", blurb: "Cut for the big screen"),
        ]),
        ("Colourful", [
            .init(iconName: "AppIcon-Prism", title: "Prism", blurb: "Every colour at once"),
            .init(iconName: "AppIcon-Sherbet", title: "Sherbet", blurb: "Three scoops"),
            .init(iconName: "AppIcon-Neon", title: "Neon", blurb: "Open all night"),
            .init(iconName: "AppIcon-Citrus", title: "Citrus", blurb: "Freshly squeezed"),
            .init(iconName: "AppIcon-Aurora", title: "Aurora", blurb: "Lights out, lights up"),
            .init(iconName: "AppIcon-PopArt", title: "Pop Art", blurb: "Wham! Season finale!"),
        ]),
        ("Throwbacks", [
            .init(iconName: "AppIcon-RabbitEars", title: "Rabbit Ears", blurb: "Don't touch that dial"),
            .init(iconName: "AppIcon-Glitch", title: "Glitch", blurb: "Signal lost, show found"),
            .init(iconName: "AppIcon-8Bit", title: "8-Bit", blurb: "Press start"),
            .init(iconName: "AppIcon-VHS", title: "VHS", blurb: "Be kind, rewind"),
            .init(iconName: "AppIcon-Cassette", title: "Cassette", blurb: "Rewind with a pencil"),
            .init(iconName: "AppIcon-Vinyl", title: "Vinyl", blurb: "Drop the needle"),
            .init(iconName: "AppIcon-FilmReel", title: "Film Reel", blurb: "Shot on actual film"),
            .init(iconName: "AppIcon-TestCard", title: "Test Card", blurb: "Please stand by"),
        ]),
        ("At the Movies", [
            .init(iconName: "AppIcon-ThreeD", title: "3D", blurb: "It's coming right at you"),
        ]),
        ("Under the Sea", [
            .init(iconName: "AppIcon-Jelly", title: "Jelly", blurb: "Say hi to the locals"),
            .init(iconName: "AppIcon-CoralReef", title: "Coral Reef", blurb: "Colour graded by nature"),
        ]),
        ("After Dark", [
            .init(iconName: "AppIcon-Midnight", title: "Midnight", blurb: "For the 2 a.m. episode"),
            .init(iconName: "AppIcon-SunsetDrive", title: "Sunset Drive", blurb: "Outrun the end credits"),
            .init(iconName: "AppIcon-Galaxy", title: "Galaxy", blurb: "Binge across the universe"),
            .init(iconName: "AppIcon-Eclipse", title: "Eclipse", blurb: "Totality worth the wait"),
            .init(iconName: "AppIcon-Lighthouse", title: "Lighthouse", blurb: "Keeps a light on for you"),
            .init(iconName: "AppIcon-Campfire", title: "Campfire", blurb: "Tell me a story"),
            .init(iconName: "AppIcon-RainyDay", title: "Rainy Day", blurb: "Perfect weather for it"),
            .init(iconName: "AppIcon-CityLights", title: "City Lights", blurb: "Downtown, after hours"),
        ]),
        ("Wildcards", [
            .init(iconName: "AppIcon-Popcorn", title: "Popcorn", blurb: "Extra butter"),
            .init(iconName: "AppIcon-CouchPotato", title: "Couch Potato", blurb: "Just one more episode"),
        ]),
    ]

    /// Offered only from a month before their holiday to a month after.
    static let seasonal: [AppIconChoice] = [
        .init(iconName: "AppIcon-NewYear", title: "New Year", blurb: "Cheers to the next season", holiday: .newYear),
        .init(iconName: "AppIcon-BurnsNight", title: "Burns Night", blurb: "A wee dram, a double bill", holiday: .burnsNight),
        .init(iconName: "AppIcon-Valentine", title: "Valentine's", blurb: "Be mine, one more episode", holiday: .valentine),
        .init(iconName: "AppIcon-MardiGras", title: "Mardi Gras", blurb: "Let the good times roll", holiday: .mardiGras),
        .init(iconName: "AppIcon-StPatrick", title: "St. Patrick's", blurb: "Sláinte!", holiday: .stPatrick),
        .init(iconName: "AppIcon-EarthDay", title: "Earth Day", blurb: "Streaming, sustainably", holiday: .earthDay),
        .init(iconName: "AppIcon-KingsDay", title: "King's Day", blurb: "Oranje boven", holiday: .kingsDay),
        .init(iconName: "AppIcon-MothersDay", title: "Mother's Day", blurb: "Picked just for you", holiday: .mothersDay),
        .init(iconName: "AppIcon-Repubblica", title: "Festa della Repubblica", blurb: "Buona visione!", holiday: .repubblica),
        .init(iconName: "AppIcon-FathersDay", title: "Father's Day", blurb: "Dad's pick tonight", holiday: .fathersDay),
        .init(iconName: "AppIcon-Midsummer", title: "Midsummer", blurb: "Dance round the maypole", holiday: .midsummer),
        .init(iconName: "AppIcon-CanadaDay", title: "Canada Day", blurb: "True north, strong stream", holiday: .canadaDay),
        .init(iconName: "AppIcon-FourthOfJuly", title: "Fourth of July", blurb: "Land of the free trial", holiday: .fourthOfJuly),
        .init(iconName: "AppIcon-BastilleDay", title: "Bastille Day", blurb: "Liberté, égalité, streamé", holiday: .bastilleDay),
        .init(iconName: "AppIcon-VivaMexico", title: "Viva México", blurb: "¡Que viva la función!", holiday: .vivaMexico),
        .init(iconName: "AppIcon-Oktoberfest", title: "Oktoberfest", blurb: "O'zapft is!", holiday: .oktoberfest),
        .init(iconName: "AppIcon-Halloween", title: "Halloween", blurb: "Trick or stream", holiday: .halloween),
        .init(iconName: "AppIcon-BonfireNight", title: "Bonfire Night", blurb: "Remember, remember", holiday: .bonfireNight),
        .init(iconName: "AppIcon-Thanksgiving", title: "Thanksgiving", blurb: "Seconds, anyone?", holiday: .thanksgiving),
        .init(iconName: "AppIcon-Christmas", title: "Christmas", blurb: "Home for the holidays", holiday: .christmas),
        .init(iconName: "AppIcon-LunarNewYear", title: "Lunar New Year", blurb: "Happy Lunar New Year", holiday: .lunarNewYear),
        .init(iconName: "AppIcon-Purim", title: "Purim", blurb: "Chag Purim sameach", holiday: .purim),
        .init(iconName: "AppIcon-Nowruz", title: "Nowruz", blurb: "Nowruz mobarak", holiday: .nowruz),
        .init(iconName: "AppIcon-Ramadan", title: "Ramadan", blurb: "Ramadan kareem", holiday: .ramadan),
        .init(iconName: "AppIcon-EidAlFitr", title: "Eid al-Fitr", blurb: "Eid Mubarak", holiday: .eidAlFitr),
        .init(iconName: "AppIcon-Holi", title: "Holi", blurb: "Happy Holi", holiday: .holi),
        .init(iconName: "AppIcon-Passover", title: "Passover", blurb: "Chag Pesach sameach", holiday: .passover),
        .init(iconName: "AppIcon-Easter", title: "Easter", blurb: "Happy Easter", holiday: .easter),
        .init(iconName: "AppIcon-Vaisakhi", title: "Vaisakhi", blurb: "Vaisakhi diyan vadhaiyan", holiday: .vaisakhi),
        .init(iconName: "AppIcon-Vesak", title: "Vesak", blurb: "Happy Vesak", holiday: .vesak),
        .init(iconName: "AppIcon-EidAlAdha", title: "Eid al-Adha", blurb: "Eid al-Adha Mubarak", holiday: .eidAlAdha),
        .init(iconName: "AppIcon-RoshHashanah", title: "Rosh Hashanah", blurb: "Shana tova", holiday: .roshHashanah),
        .init(iconName: "AppIcon-MidAutumn", title: "Mid-Autumn", blurb: "Happy Mid-Autumn Festival", holiday: .midAutumn),
        .init(iconName: "AppIcon-DiaDeMuertos", title: "Día de Muertos", blurb: "Feliz Día de Muertos", holiday: .diaDeMuertos),
        .init(iconName: "AppIcon-Diwali", title: "Diwali", blurb: "Happy Diwali", holiday: .diwali),
        .init(iconName: "AppIcon-Hanukkah", title: "Hanukkah", blurb: "Happy Hanukkah", holiday: .hanukkah),
        .init(iconName: "AppIcon-Kwanzaa", title: "Kwanzaa", blurb: "Happy Kwanzaa", holiday: .kwanzaa),
    ]
}
#endif
